Also dump stderr to /dev/null
Otherwise the traceback that normally gets logged gets dumped into the
output, which GHA then points out in a test annotation (the test still
succeeds because it exits zero):

```
Failed to connect to the LIGO LDAP
Traceback (most recent call last):
  File "/home/runner/work/topology/topology/src/stashcache.py", line 57, in _generate_ligo_dns
    conn.bind()
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/ldap3/core/connection.py", line 604, in bind
    request = bind_operation(self.version, self.authentication, self.user, self.password, auto_encode=self.auto_encode)
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/ldap3/operation/bind.py", line 59, in bind_operation
Error:     raise LDAPPasswordIsMandatoryError('password is mandatory in simple bind')
ldap3.core.exceptions.LDAPPasswordIsMandatoryError: password is mandatory in simple bind
```